name: whoodata
description: Event-first people remembering app with optional business card OCR
publish_to: "none"
version: 0.1.2+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  collection: ^1.18.0
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0
  google_mlkit_text_recognition: ^0.13.0
  image: ^4.2.0
  image_picker: ^1.1.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  share_plus: ^10.0.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  url_launcher: ^6.3.0
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/default/logo.png
